version: "3.1"
services:
    db:
        container_name: application-db
        image: mariadb
        working_dir: /application
        volumes:
            - .database:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_DATABASE=application
            - MYSQL_USER=application
            - MYSQL_PASSWORD=secret            
        ports:
        - "8083:3306"

    adminer:
        container_name: application-adminer
        image: adminer
        ports:
            - 8000:8080

    web:
        container_name: application-web
        image: nginx:alpine
        working_dir: /application
        volumes:
            - .:/application
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/site.conf
        ports:
            - 8080:80

    php:
        container_name: application-php
        build: docker/php-fpm
        volumes:
            - .:/application
            - ./docker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/custom.d/php.ini
        environment:
            PHP_INI_SCAN_DIR: "/usr/local/etc/php/custom.d:/usr/local/etc/php/conf.d"
